# Generated by Django 6.0.3 on 2026-04-06 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_jobs', models.IntegerField(default=0)),
                ('successful', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='JobResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('email_status', models.BooleanField(default=False)),
                ('retries', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_results', to='django_admin.pipelinerun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
